# Generated by Django 5.0 on 2024-01-15 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='author',
        ),
    ]
