# Generated by Django 5.0 on 2024-01-16 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_userpurchase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpurchase',
            old_name='user',
            new_name='author',
        ),
    ]
